const mongoose = require("mongoose");

// ─── paste your MONGO_URI here or load from .env ───────────────────────────
const MONGO_URI = "mongodb+srv://ranesons11:SEycv5RPk65Y1xOY@cluster0.et6jd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";

// ─── paste a valid admin _id from your users collection ────────────────────
const ADMIN_ID = "67b497c8ef3b0e7038185a8a";

// ─── inline model (so seed script is self-contained) ───────────────────────
const sorItemSchema = new mongoose.Schema(
  {
    item_number:  { type: String, required: true },
    schedule: {
      type: String,
      required: true,
      enum: [
        "Fire Extinguishers",
        "Fire Pipes",
        "Sprinkler System",
        "Fire Alarm System",
        "Pumps & Accessories",
        "Valves & Accessories",
        "Hydrant System",
      ],
    },
    description:  { type: String, required: true },
    unit:         { type: String, required: true },
    rate_low:     { type: Number, required: true, min: 0 },
    rate_high:    { type: Number, default: null, min: 0 },
    version:      { type: Number, default: 1 },
    is_latest:    { type: Boolean, default: true },
    updated_by:   { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    updated_at:   { type: Date, default: Date.now },
  },
  { timestamps: true }
);
const SorItem = mongoose.model("SorItem", sorItemSchema);

// ─── all items extracted from the PDF ──────────────────────────────────────
const sorData = [

  // ── Schedule A: Fire Extinguishers ────────────────────────────────────────
  {
    item_number: "1",
    schedule: "Fire Extinguishers",
    description: "ABC Fire Extinguisher up to 6 kg – Installation & fixing",
    unit: "Each",
    rate_low: 100,
    rate_high: 120,
  },
  {
    item_number: "2",
    schedule: "Fire Extinguishers",
    description: "ABC Fire Extinguisher above 6 kg – Installation & fixing",
    unit: "Each",
    rate_low: 120,
    rate_high: 150,
  },
  {
    item_number: "3",
    schedule: "Fire Extinguishers",
    description: "CO₂ Fire Extinguisher installation",
    unit: "Each",
    rate_low: 100,
    rate_high: null,
  },
  {
    item_number: "4",
    schedule: "Fire Extinguishers",
    description: "DCP / Trolley Type Fire Extinguisher",
    unit: "Each",
    rate_low: 200,
    rate_high: 450,
  },
  {
    item_number: "5",
    schedule: "Fire Extinguishers",
    description: "Fire Extinguisher stand / bracket fixing",
    unit: "Each",
    rate_low: 70,
    rate_high: 130,
  },

  // ── Schedule B: Fire Pipes ────────────────────────────────────────────────
  {
    item_number: "6",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 200mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 800,
    rate_high: 820,
  },
  {
    item_number: "7",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 150mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 620,
    rate_high: 640,
  },
  {
    item_number: "8",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 100mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 420,
    rate_high: 460,
  },
  {
    item_number: "9",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 80mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 270,
    rate_high: 300,
  },
  {
    item_number: "10",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 65mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 250,
    rate_high: 275,
  },
  {
    item_number: "11",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 50mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 200,
    rate_high: 230,
  },
  {
    item_number: "12",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 40mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 140,
    rate_high: 150,
  },
  {
    item_number: "13",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 32mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 145,
    rate_high: null,
  },
  {
    item_number: "14",
    schedule: "Fire Pipes",
    description: "Providing, fixing, testing and commissioning of above ground 25mm dia. GI/MS Class-B/C pipes with cutting, screwing, welding if required and providing all structural work fabricated from standard sections (MS rounds, angles, channels etc.), and fittings like flanges, bends, tees, elbows, reducers, clamps, hangers, fasteners etc.",
    unit: "Meter",
    rate_low: 125,
    rate_high: null,
  },

  // ── Schedule C: Sprinkler System ──────────────────────────────────────────
  {
    item_number: "15",
    schedule: "Sprinkler System",
    description: "Sprinkler head fixing – Providing, fixing, testing & commissioning of pendent/sidewall fire sprinklers (UL approved) of 15mm dia size",
    unit: "Each",
    rate_low: 50,
    rate_high: 80,
  },
  {
    item_number: "15.A",
    schedule: "Sprinkler System",
    description: "Installation, testing & commissioning of adjustable rosette plate for 15mm dia in white finish UL Listed or FM approved complete as required",
    unit: "Each",
    rate_low: 50,
    rate_high: null,
  },
  {
    item_number: "16",
    schedule: "Sprinkler System",
    description: "Riser / Branch line installation",
    unit: "Rmt",
    rate_low: 150,
    rate_high: null,
  },
  {
    item_number: "17",
    schedule: "Sprinkler System",
    description: "Flow switch installation",
    unit: "Each",
    rate_low: 90,
    rate_high: null,
  },
  {
    item_number: "18",
    schedule: "Sprinkler System",
    description: "Pressure switch installation",
    unit: "Each",
    rate_low: 50,
    rate_high: 100,
  },

  // ── Schedule D: Fire Alarm System ─────────────────────────────────────────
  {
    item_number: "19",
    schedule: "Fire Alarm System",
    description: "Smoke / Heat Detector – Supply, Installation, Testing & Commissioning of conventional type smoke detectors with necessary wiring, piping and fittings complete",
    unit: "Each",
    rate_low: 90,
    rate_high: 120,
  },
  {
    item_number: "20",
    schedule: "Fire Alarm System",
    description: "Manual Call Point (MCP) installation – Supply, Installation, Testing & Commissioning of conventional type manual call point with necessary wiring and fittings complete",
    unit: "Each",
    rate_low: 100,
    rate_high: 120,
  },
  {
    item_number: "21",
    schedule: "Fire Alarm System",
    description: "Hooter / Sounder installation – Supply, Installation, Testing & Commissioning of conventional type hooter cum sounder with necessary wiring and fittings complete",
    unit: "Each",
    rate_low: 100,
    rate_high: 120,
  },
  {
    item_number: "22",
    schedule: "Fire Alarm System",
    description: "Fire Alarm Panel installation & mounting – Supply, Installation, Testing & Commissioning of conventional type 8/16/32/64 zone fire alarm panel with complete required fittings",
    unit: "Each",
    rate_low: 3500,
    rate_high: 5000,
  },
  {
    item_number: "22.A",
    schedule: "Fire Alarm System",
    description: "Fire Signage – Fixing different type content auto glow photoluminescent signages",
    unit: "Each",
    rate_low: 25,
    rate_high: 50,
  },
  {
    item_number: "23",
    schedule: "Fire Alarm System",
    description: "Fire alarm cabling (surface / conduit) – Supply, installation, testing and commissioning of cable 2 Core x 1.5 sqmm complete with casing pipe & fittings etc.",
    unit: "Meter",
    rate_low: 25,
    rate_high: 38,
  },

  // ── Schedule E: Pumps & Accessories ──────────────────────────────────────
  {
    item_number: "24",
    schedule: "Pumps & Accessories",
    description: "Fire Pump installation (Main) – Supplying, installation, testing and commissioning of electric driven hydrant pump suitable for automatic operation. Note: Depends on pump capacity.",
    unit: "Each",
    rate_low: 20000,
    rate_high: 40000,
  },
  {
    item_number: "25",
    schedule: "Pumps & Accessories",
    description: "Fire Pump installation (Jockey) – Supplying, installation, testing and commissioning of electric driven pressurization jockey pump suitable for automatic operation. Note: Depends on pump capacity.",
    unit: "Each",
    rate_low: 12000,
    rate_high: 20000,
  },
  {
    item_number: "26",
    schedule: "Pumps & Accessories",
    description: "Installation, testing and commissioning of main diesel engine pump with bronze impeller and mechanical seal fitted, with 100 litre fuel tank. Note: Depends on pump capacity.",
    unit: "Each",
    rate_low: 35000,
    rate_high: 50000,
  },
  {
    item_number: "27",
    schedule: "Pumps & Accessories",
    description: "Fire Pump Panel – Installing, testing and commissioning of common control panel suitable for auto start and stop of fire pump (main fire pump & jockey pump) with provision of push buttons for manual operation",
    unit: "Each",
    rate_low: 8000,
    rate_high: 25000,
  },
  {
    item_number: "28",
    schedule: "Pumps & Accessories",
    description: "Pump alignment & commissioning support – MS fabricated common base plate, coupling, coupling guard, foundation bolts etc. as required. Suitable cement concrete foundation duly plastered and with anti-vibration pads.",
    unit: "Set",
    rate_low: 2500,
    rate_high: null,
  },
  {
    item_number: "28.A",
    schedule: "Pumps & Accessories",
    description: "Pressure Gauge installation",
    unit: "Each",
    rate_low: 50,
    rate_high: 80,
  },
  {
    item_number: "28.B",
    schedule: "Pumps & Accessories",
    description: "Flow Meter installation",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },

  // ── Schedule F: Valves & Accessories ─────────────────────────────────────
  {
    item_number: "29",
    schedule: "Valves & Accessories",
    description: "Installation, testing and commissioning of air vessel tank made of 250mm dia, 1200mm in height with air release valve on top & drain arrangement with 25mm dia ball valve, with required accessories, pressure gauge and painting with synthetic enamel paint. Note: Depends on pump capacity.",
    unit: "Each",
    rate_low: 6750,
    rate_high: 9000,
  },
  // Y-Strainers (item 30.x)
  {
    item_number: "30.1",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 15mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "30.2",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 25mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "30.3",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 50mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "30.4",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 100mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 400,
    rate_high: 450,
  },
  {
    item_number: "30.5",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 150mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 450,
    rate_high: 500,
  },
  {
    item_number: "30.6",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 250mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 600,
    rate_high: null,
  },
  {
    item_number: "30.7",
    schedule: "Valves & Accessories",
    description: "Y-Strainer 300mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 680,
    rate_high: null,
  },
  // NRV (item 31.x)
  {
    item_number: "31.1",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 15mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 250,
    rate_high: 300,
  },
  {
    item_number: "31.2",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 20mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: 320,
  },
  {
    item_number: "31.3",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 25mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 320,
    rate_high: null,
  },
  {
    item_number: "31.4",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 32mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 320,
    rate_high: null,
  },
  {
    item_number: "31.5",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 40mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 320,
    rate_high: null,
  },
  {
    item_number: "31.6",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 50mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 330,
    rate_high: null,
  },
  {
    item_number: "31.7",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 65mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 350,
    rate_high: null,
  },
  {
    item_number: "31.8",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 80mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 350,
    rate_high: 400,
  },
  {
    item_number: "31.9",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 100mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 400,
    rate_high: 450,
  },
  {
    item_number: "31.10",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 150mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 450,
    rate_high: 500,
  },
  {
    item_number: "31.11",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 200mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 600,
    rate_high: null,
  },
  {
    item_number: "31.12",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 250mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 680,
    rate_high: null,
  },
  {
    item_number: "31.13",
    schedule: "Valves & Accessories",
    description: "NRV (Non Return Valve) 300mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 800,
    rate_high: null,
  },
  // Rubber Expansion Bellows (item 32.x)
  {
    item_number: "32.1",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 25mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.2",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 32mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.3",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 40mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.4",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 50mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.5",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 65mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.6",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 80mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: null,
  },
  {
    item_number: "32.7",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 100mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 400,
    rate_high: 450,
  },
  {
    item_number: "32.8",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 150mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 450,
    rate_high: 500,
  },
  {
    item_number: "32.9",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 200mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 650,
    rate_high: null,
  },
  {
    item_number: "32.10",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 250mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 700,
    rate_high: null,
  },
  {
    item_number: "32.11",
    schedule: "Valves & Accessories",
    description: "Rubber Expansion Bellow 300mm Dia – Installation, testing and commissioning, ISI marked complete with nuts, bolts, washers, gaskets etc.",
    unit: "Each",
    rate_low: 900,
    rate_high: null,
  },
  {
    item_number: "33",
    schedule: "Valves & Accessories",
    description: "Installation, testing and commissioning of Air Vent valve (Air release valve) all dia, ISI marked complete with nipples, sockets, ball valve complete.",
    unit: "Each",
    rate_low: 400,
    rate_high: null,
  },
  // Butterfly Valves (item 34.x)
  {
    item_number: "34.1",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 15mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 150,
    rate_high: 200,
  },
  {
    item_number: "34.2",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 25mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 250,
    rate_high: 300,
  },
  {
    item_number: "34.3",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 32mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 250,
    rate_high: 300,
  },
  {
    item_number: "34.4",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 40mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 250,
    rate_high: 300,
  },
  {
    item_number: "34.5",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 50mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 250,
    rate_high: 300,
  },
  {
    item_number: "34.6",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 65mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 275,
    rate_high: 300,
  },
  {
    item_number: "34.7",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 80mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: 400,
  },
  {
    item_number: "34.8",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 100mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: 400,
  },
  {
    item_number: "34.9",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 150mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 300,
    rate_high: 400,
  },
  {
    item_number: "34.10",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 200mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 500,
    rate_high: null,
  },
  {
    item_number: "34.11",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 250mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 780,
    rate_high: null,
  },
  {
    item_number: "34.12",
    schedule: "Valves & Accessories",
    description: "Butterfly Valve 300mm Dia – EPDM lined CI, BS slim seal standard lever operated type with required flanges, nuts, bolts etc.",
    unit: "Each",
    rate_low: 800,
    rate_high: null,
  },
  {
    item_number: "35",
    schedule: "Valves & Accessories",
    description: "2 Way Inlet – Installing and commissioning of fire brigade inlet connection of 2 way, 63mm dia.",
    unit: "Each",
    rate_low: 500,
    rate_high: null,
  },
  {
    item_number: "36",
    schedule: "Valves & Accessories",
    description: "4 Way Inlet – Installing and commissioning of fire brigade inlet connection of 4 way, 63mm dia.",
    unit: "Each",
    rate_low: 500,
    rate_high: null,
  },
  {
    item_number: "37",
    schedule: "Valves & Accessories",
    description: "Ball Valve 25mm – Installation",
    unit: "Each",
    rate_low: 50,
    rate_high: null,
  },

  // ── Schedule G: Hydrant System ────────────────────────────────────────────
  {
    item_number: "38",
    schedule: "Hydrant System",
    description: "Hydrant Valve SS – Fixing, testing and commissioning of single headed oblique pattern hydrant landing valves as per IS:5290 and ISI with 80mm dia flanged inlet & 63mm dia female outlet complete with cap",
    unit: "Each",
    rate_low: 500,
    rate_high: 600,
  },
  {
    item_number: "39",
    schedule: "Hydrant System",
    description: "Hose Box Double Door – Fixing, testing and commissioning of standard fire hose cabinet wall mounting type having double door opening with necessary locking arrangement by Allen key",
    unit: "Each",
    rate_low: 400,
    rate_high: 500,
  },
  {
    item_number: "40",
    schedule: "Hydrant System",
    description: "Hose Pipe RRL 15 Mtr. Long – Providing & fixing of stainless-steel single headed internal hydrant valve with 80mm NB flanged inlet, brass spindle controlled 63mm dia female instantaneous outlet type",
    unit: "Each",
    rate_low: 500,
    rate_high: null,
  },
  {
    item_number: "41",
    schedule: "Hydrant System",
    description: "Hose Reel Drum 30 Mtr Long 25mm – Providing & fixing swinging type first aid hose reel in red color drum with 36 mtrs long and 20mm dia heavy duty rubber water hose, water flow rate 24 LPM at 7 Kg/CM², jet range 6 mtr, terminating with SS coupling & nozzle of 6mm outlet with shut off valve confirming to IS 8090-1976 complete with MS socket for tap-off, drum and bracket",
    unit: "Each",
    rate_low: 50,
    rate_high: 100,
  },
  {
    item_number: "42",
    schedule: "Hydrant System",
    description: "Branch Pipe SS – Providing, fixing, testing and commissioning of standard SS branch pipe with nozzle of 20mm nominal bore outlet as per IS:903 suitable to fit with standard instantaneous type 63mm dia coupling",
    unit: "Each",
    rate_low: 45,
    rate_high: 50,
  },
  {
    item_number: "43",
    schedule: "Hydrant System",
    description: "Yard Hydrant – Installation, testing and commissioning",
    unit: "Each",
    rate_low: 900,
    rate_high: 1200,
  },
];

// ─── seed function ──────────────────────────────────────────────────────────
async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing seed data (only version 1 / is_latest items)
    await SorItem.deleteMany({ version: 1 });
    console.log("🗑️  Cleared existing v1 items");

    // Attach admin id and insert
    const docs = sorData.map((item) => ({
      ...item,
      version: 1,
      is_latest: true,
      updated_by: new mongoose.Types.ObjectId(ADMIN_ID),
      updated_at: new Date("2026-02-05T15:57:44.000Z"), // matches PDF sign date
    }));

    await SorItem.insertMany(docs);
    console.log(`✅ Inserted ${docs.length} SOR items successfully`);

  } catch (err) {
    console.error("❌ Seed failed:", err.message);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
  }
}

seed();